export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const GET_USER_LOCATION = 'GET_USER_LOCATION';
export const SET_MAIN_BACKGROUND = 'SET_MAIN_BACKGROUND';
export const GET_WEATHER = 'GET_WEATHER';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';